AllCops:
  Exclude:
    - vendor/**
    - bin/**

LineLength:
  Enabled: false

MethodLength:
  Enabled: false

ClassLength:
  Enabled: false

Documentation:
  # don't require classes to be documented
  Enabled: false

CollectionMethods:
  # don't prefer map to collect, recuce to inject
  Enabled: false

Encoding:
  # no need to always specify encoding
  Enabled: false

FileName:
  # allow grape-roar.rb
  Enabled: false
